# -*- coding: utf-8 -*-
"""image_classification_using_cnn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SJ-idzn99ylyUVBAEmjPkCBd5YRFA-iF

# 1.0 Convolutional Neural Network (CNN)

A **Convolutional Neural Network (ConvNet/CNN)** is a Deep Learning algorithm which can take in an input image, assign importance (learnable weights and biases) to various aspects/objects in the image and be able to differentiate one from the other. The pre-processing required in a ConvNet is much lower as compared to other classification algorithms. While in primitive methods filters are hand-engineered, with enough training, ConvNets have the ability to learn these filters/characteristics.

![CNN](https://i.imgur.com/jmV3oAz.jpg)

In this notebook, I will be using Convolutional Neural Network(CNN) to classify [CIFAR images](https://www.cs.toronto.edu/~kriz/cifar.html).<p>I will be using the [Keras Sequential API](https://www.tensorflow.org/guide/keras/overview), creating and training the model will take just a few lines of code.

## 1.1 Importing libraries
"""

# Import TensorFlow
import tensorflow as tf
from tensorflow.keras import datasets, layers, models
import matplotlib.pyplot as plt

"""## 1.2 Loading data


The **CIFAR10** dataset contains 60,000 color images in 10 classes, with 6,000 images in each class. The dataset is divided into 50,000 training images and 10,000 testing images. The classes are mutually exclusive and there is no overlap between them.
"""

(train_images, train_labels), (test_images, test_labels) = datasets.cifar10.load_data()

# Normalize pixel values to be between 0 and 1
# Why is this done?
# Improves numerical stability
# Faster convergenc
# Consistent input distribution
train_images, test_images = train_images / 255.0, test_images / 255.0

train_images.shape

"""To verify that the dataset looks correct, let's plot the first 25 images from the training set and display the class name below each image."""

class_names = ['airplane', 'automobile', 'bird', 'cat', 'deer',
               'dog', 'frog', 'horse', 'ship', 'truck']

plt.figure(figsize=(8,8))
for i in range(25):
    plt.subplot(5,5,i+1)
    plt.xticks([])
    plt.yticks([])
    plt.imshow(train_images[i])
    # The CIFAR labels happen to be arrays,
    #which is why we need the extra index
    plt.xlabel(class_names[train_labels[i][0]])
plt.show()

"""## 1.3 Create the convolutional base

The 6 lines of code below define the convolutional base using a common pattern: a stack of [Conv2D](https://keras.io/api/layers/convolution_layers/convolution2d/) and [MaxPooling2D](https://keras.io/api/layers/pooling_layers/max_pooling2d/) layers.

As input, a CNN takes tensors of shape (image_height, image_width, color_channels), ignoring the batch size. If you are new to these dimensions, color_channels refers to (R,G,B). In this example, you will configure our CNN to process inputs of shape (32, 32, 3), which is the format of CIFAR images. You can do this by passing the argument **input_shape** to our first layer.
"""

model = models.Sequential()
model.add(layers.Conv2D(32, (3, 3), activation='relu', input_shape=(32, 32, 3)))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(64, (3, 3), activation='relu'))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(64, (3, 3), activation='relu'))

"""Now, let's display the architecture of our model."""

model.summary()
# This column shows the shape of the output from each layer. The first dimension (None) refers to the batch size, which can vary during training.
#  The rest of the dimensions represent the spatial dimensions (height, width) and the number of channels (also called filters).

# Parameters = (3x3x3 + 1) x 32 = 896.                               +1 for a bias term
# Parameters = (3x3x32 + 1) x 64 = 18,496.
# Parameters = (3x3x64 + 1) x 64 = 36,928.

"""Above, we can see that the output of every Conv2D and MaxPooling2D layer is a 3D tensor of shape (height, width, channels). The width and height dimensions tend to shrink as you go deeper in the network. The number of output channels for each Conv2D layer is controlled by the first argument (e.g., 32 or 64).

## 1.4 Adding Dense Layers on the top
To complete our model, you will feed the last output tensor from the convolutional base (of shape (4, 4, 64)) into one or more **Dense layers** to perform classification. Dense layers take vectors as input (which are 1D), while the current output is a 3D tensor. First, you will flatten (or unroll) the 3D output to 1D,  then add one or more Dense layers on top. CIFAR has 10 output classes, so you use a final Dense layer with 10 outputs.
"""

model.add(layers.Flatten())
model.add(layers.Dense(64, activation='relu'))
model.add(layers.Dense(10))

"""Here's the complete architecture of our model."""

model.summary()

"""So our (4, 4, 64) outputs were flattened into vectors of shape (1024) before going through two Dense layers.

## 1.5 Compile and train the model
"""

# Adam is the best among the adaptive optimizers in most of the cases
# Key Features of Adam:
# Adaptive Learning Rates           Momentum                   Bias Correction
model.compile(optimizer='adam',
              # By setting from_logits=True, you're telling TensorFlow that the model's output is raw logits (i.e., not probabilities) and that the loss function should apply the softmax transformation internally.
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])

# An epoch means training the neural network with all the
# training data for one cycle. Here I use 10 epochs
history = model.fit(train_images, train_labels, epochs=10,
                    validation_data=(test_images, test_labels))


# Why it's important:(Valditoin loss)
# The training loss could decrease over time because the model is getting better at fitting the training data, but it may start overfitting.
# Validation loss helps you monitor how well the model generalizes to unseen data. If val_loss starts increasing while training_loss keeps decreasing, it's a sign that your model is overfitting.
# tsa3dny bardo lw ana 3ayz a3ml early stoping

# val_accuracy: Measures how accurate the model is on the validation set. Higher is better.

"""## 1.6 Evaluate the model"""

plt.plot(history.history['accuracy'],label='accuracy')
plt.plot(history.history['val_accuracy'],label = 'val_accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
# Here, it's setting the y-axis to range between 0.5 and 1, which is often useful when plotting accuracy or some performance metric that falls between 0 and 1 (like percentages or probabilities).
# 0.5 is the lower bound (50%)  - ----   1 is the upper bound (100%)      >>>>   This ensures that any accuracy values below 50% will not be shown in the plot.
plt.ylim([0.5, 1])
plt.legend(loc='lower right')                   # The loc='lower right' argument positions the legend in the lower right corner of the plot.

test_loss, test_acc = model.evaluate(test_images,
                                     test_labels,
                                     verbose=2)


# model.evaluate() takes in two arguments:
# test_images: The test images that the model will use for evaluation.
# test_labels: The corresponding ground-truth labels for those test images.
# Return values:
# test_loss: The loss on the test data. It tells you how far off the model’s predictions were from the true labels (on average).
# test_acc: The accuracy of the model on the test data. This gives the proportion of correctly classified images out of the total test set.
# verbose=2 controls the level of output. With verbose=2, you get more detailed output during the evaluation (showing loss and accuracy after the process is done).
# verbose=0: No output at all.
# verbose=1: Displays a progress bar with updates after each batch during training or evaluation.
# verbose=2: Displays a summary for each epoch without showing batch-by-batch progress.

print('Test Accuracy is',test_acc)

"""This simple CNN has achieved a test accuracy of over 70%, which is not bad.

**Thank you**
"""

